#!/usr/bin/env python

import sys

def readfile(p):
    with open(p, 'rb') as f:
        x = f.read()
    return x

def writefile(p, s):
    with open(p, 'wb') as f:
        f.write(s.replace('\r', '\n'))

to_unix = lambda s: s.replace('\r', '\n')

replacefile_as_unix = lambda p: writefile(p, to_unix(readfile(p)))

if __name__ == '__main__':
    print(', '.join(sys.argv[1::]))
    for p in sys.argv[1::]:
        replacefile_as_unix(p)

